:ambulance: Update PostgreSQL service scripts and improve project documentation
This commit overhauls the PostgreSQL service start script, enhancing its error handling, adding Docker requirements checking, improving directory ownership management, and introducing more robust PostgreSQL configuration. It also includes creating helpful README files for the project's temp directory in both English and Chinese. Information related to temporary files' handling and guidelines are described. In addition, this update includes a new PostgreSQL configuration file as well as ample changes in Docker command instructions in the documentation. The commit aims to streamline the running of the Docker services and provide more contextual information about the project's structures and configurations.

diff --git a/scripts/docker/002-postgresql-service/start-postgresql-service b/scripts/docker/002-postgresql-service/start-postgresql-service
--- a/scripts/docker/002-postgresql-service/start-postgresql-service
+++ b/scripts/docker/002-postgresql-service/start-postgresql-service
@@ -1,10 +1,9 @@
 #!/bin/bash
-# File: start-postgresql-service
-# Editor: PyCharm
-# Author: Austin (From Chengdu.China) https://fairy.host
-# HomePage: https://github.com/AustinFairyland
-# OperatingSystem: Windows 11 Professional Workstation 23H2 Canary Channel
-# CreatedTime: 12/22/2023
+# @software: PyCharm
+# @author: Lionel Johnson
+# @contact: https://fairy.host
+# @organization: https://github.com/FairylandFuture
+# @since: 2024-06-22 13:40:00 UTC+8
 
 # Terminal output color
 RESET_COLOR="\e[0m"
@@ -17,29 +16,49 @@ CONTAINER_NAME="postgresql-service"
 CONTAINER_USER="$(id -u)"
 CONTAINER_GROUP="$(id -g)"
 DOCKER_VOLUME_DIR="/data/container/volume"
-DOCKER_CONTRAINER_ENV="/data/container/env.d"
 
-POSTGRESQL_CONF_FILE="${EXECUTE_PATH}/conf.d/postgresql.conf"
+POSTGRESQL_CONF_FILE_PATH="${EXECUTE_PATH}/conf.d/postgresql.conf"
+POSTGRESQL_DEFAULT_PASSWORD="Y14Ok3C5W5f5zx0L"
 
-LOCAL_POSTGRESQL_CONF_PATH="${DOCKER_VOLUME_DIR}/${CONTAINER_NAME}/conf"
-LOCAL_POSTGRESQL_DATA_PATH="${DOCKER_VOLUME_DIR}/${CONTAINER_NAME}/data"
+LOCAL_POSTGRESQL_CONF_DIR_PATH="${DOCKER_VOLUME_DIR}/${CONTAINER_NAME}/conf"
+LOCAL_POSTGRESQL_DATA_DIR_PATH="${DOCKER_VOLUME_DIR}/${CONTAINER_NAME}/data"
+
+check_requirements() {
+  if ! command -v docker &>/dev/null; then
+    echo -e "${RED_COLOR}Docker is not installed. Please install Docker and try again.${RESET_COLOR}"
+    exit 1
+  fi
+}
 
 check_directory() {
   local dir_path=$1
   if [ -d "$dir_path" ]; then
-    return 0
+    echo -e "${GREEN_COLOR}Directory ${dir_path} exists.${RESET_COLOR}"
   else
     echo -e "${GREEN_COLOR}Directory ${dir_path} does not exist, creating it${RESET_COLOR}"
     if mkdir -p "$dir_path"; then
-      echo -e "${GREEN_COLOR}Directory ${dir_path} create success.${RESET_COLOR}"
-      return 0
+      echo -e "${GREEN_COLOR}Directory ${dir_path} created successfully.${RESET_COLOR}"
     else
-      return 1
+      echo -e "${RED_COLOR}Failed to create directory ${dir_path}.${RESET_COLOR}"
+      exit 1
     fi
   fi
 }
 
+change_directory_owner() {
+  local dir_path=$1
+  echo -e "${GREEN_COLOR}Changing ownership of directory ${dir_path} ...${RESET_COLOR}"
+  if sudo chown -R "$CONTAINER_USER":"$CONTAINER_GROUP" "$dir_path"; then
+    echo -e "${GREEN_COLOR}Successfully changed ownership of directory ${dir_path}.${RESET_COLOR}"
+  else
+    echo -e "${RED_COLOR}Failed to change ownership of directory ${dir_path}.${RESET_COLOR}"
+    exit 1
+  fi
+}
+
 main() {
+  check_requirements
+
   if [ "$EUID" -ne 0 ]; then
     echo -e "${RED_COLOR}The script must be run as root or with sudo.${RESET_COLOR}"
     exit
@@ -57,15 +76,24 @@ main() {
   fi
 
   # Check if the directory is empty
-  check_directory $LOCAL_POSTGRESQL_DATA_PATH
+  check_directory $LOCAL_POSTGRESQL_CONF_DIR_PATH
+  check_directory $LOCAL_POSTGRESQL_DATA_DIR_PATH
 
-  echo -e "${GREEN_COLOR}Changing ownership of the $LOCAL_POSTGRESQL_DATA_PATH ...${RESET_COLOR}"
-  if sudo chown -R "$CONTAINER_USER":"$CONTAINER_GROUP" $LOCAL_POSTGRESQL_DATA_PATH; then
-    echo -e "${GREEN_COLOR}Ownership change success.${RESET_COLOR}"
+  if [[ -f "$POSTGRESQL_CONF_FILE_PATH" ]]; then
+    echo -e "${GREEN_COLOR}File exists: ${POSTGRESQL_CONF_FILE_PATH}${RESET_COLOR}"
+    if cp "$POSTGRESQL_CONF_FILE_PATH" "$LOCAL_POSTGRESQL_CONF_DIR_PATH"; then
+      echo -e "${GREEN_COLOR}Successfully copied file.${RESET_COLOR}"
+    else
+      echo -e "${RED_COLOR}Failed to copy file.${RESET_COLOR}"
+      exit 1
+    fi
   else
-    echo -e "${RED_COLOR}Ownership change failed.${RESET_COLOR}"
-    exit
+    echo -e "${RED_COLOR}File does not exist: ${MYSQL_CONF_PATH}${RESET_COLOR}"
+    exit 1
   fi
+
+  change_directory_owner $LOCAL_POSTGRESQL_CONF_DIR_PATH
+  change_directory_owner $LOCAL_POSTGRESQL_DATA_DIR_PATH
 
   local docker_command=(
     "docker"
@@ -77,11 +105,16 @@ main() {
     "--user" "$CONTAINER_USER":"$CONTAINER_GROUP"
     "--privileged=true"
     "-e" "TZ=Asia/Shanghai"
+    "-e" "POSTGRES_USER=postgres"
+    "-e" "POSTGRES_PASSWORD=${POSTGRESQL_DEFAULT_PASSWORD}"
+    "-e" "POSTGRES_DB=postgres"
+    "-e" "PGDATA=/var/lib/postgresql/data"
     "-p" "51002:5432"
-    "-v" "${LOCAL_POSTGRESQL_DATA_PATH}:/var/lib/postgresql/data"
-    "--env-file" "${DOCKER_CONTRAINER_ENV}/postgres.env"
+    "-v" "${LOCAL_POSTGRESQL_CONF_DIR_PATH}:/etc/postgresql"
+    "-v" "${LOCAL_POSTGRESQL_DATA_DIR_PATH}:/var/lib/postgresql/data"
     "--restart" "always"
     "postgres:16.1"
+    "-c" "config_file=/etc/postgresql/postgresql.conf"
   )
 
   if "${docker_command[@]}"; then
